server :
  port : 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/report
    username: root
    password:


  jpa:
    hibernate:
      ddl-auto: update
#    properties :
#      hibernate :
#        temp :
#          use_jdbc_metadata_defaults : false
#    show-sql: true

report_folder_path : C:\client-jasper-report-folders
